version: '2'
services:
    web:
        build: .
        depends_on:
            - mongo
        env_file: .env
        environment:
            - DATABASE_URL=mongodb://mongo/db
        ports:
            - "$PORT:3000"
    mongo:
        image: mongo
